// Real Templates with actual previews
export interface ResumeTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  type: 'resume' | 'presentation';
  previewImage: string;
  previewImages?: string[]; // For presentations with multiple slides
  pdfUrl: string;
  colorScheme: string[];
  tags: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'professional';
  isPro: boolean;
  isFeatured: boolean;
  rating: number;
  downloads: number;
  author: {
    name: string;
    verified: boolean;
  };
}

export const RESUME_TEMPLATES: ResumeTemplate[] = [
  // RESUME TEMPLATES
  {
    id: 'software-engineering-resume',
    title: 'Software Engineering Resume',
    description: 'Professional software engineering resume template with clean layout. Perfect for developers and tech professionals.',
    category: 'Tech',
    type: 'resume',
    previewImage: '/templates/previews/software-engineering.png',
    pdfUrl: '/Software_Engineering_Resume.pdf',
    colorScheme: ['#2563EB', '#FFFFFF', '#1E40AF', '#60A5FA'],
    tags: ['Software Engineer', 'Developer', 'Tech', 'ATS-Friendly', 'Professional'],
    difficulty: 'professional',
    isPro: false,
    isFeatured: true,
    rating: 4.9,
    downloads: 18500,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'nit-patna-resume',
    title: 'NIT Patna Resume Template',
    description: 'Academic resume template from NIT Patna. Clean and professional layout for students and fresh graduates.',
    category: 'Academic',
    type: 'resume',
    previewImage: '/templates/previews/nit-patna.png',
    pdfUrl: '/NIT_Patna_Resume_Template_v2_1.pdf',
    colorScheme: ['#1F2937', '#FFFFFF', '#374151', '#6B7280'],
    tags: ['Academic', 'Student', 'Fresh Graduate', 'University', 'Clean'],
    difficulty: 'beginner',
    isPro: false,
    isFeatured: true,
    rating: 4.8,
    downloads: 12300,
    author: {
      name: 'NIT Patna',
      verified: true,
    },
  },
  {
    id: 'deedy-resume',
    title: 'Deedy Resume (Reversed)',
    description: 'Popular Deedy resume template with reversed layout. Modern and eye-catching design for tech professionals.',
    category: 'Modern',
    type: 'resume',
    previewImage: '/templates/previews/deedy.png',
    pdfUrl: '/Deedy_Resume_Reversed.pdf',
    colorScheme: ['#0EA5E9', '#FFFFFF', '#0284C7', '#38BDF8'],
    tags: ['Modern', 'Tech', 'Creative', 'Two-Column', 'Popular'],
    difficulty: 'intermediate',
    isPro: false,
    isFeatured: true,
    rating: 4.9,
    downloads: 25600,
    author: {
      name: 'Deedy',
      verified: true,
    },
  },
  {
    id: 'autocv-template',
    title: 'AutoCV Template',
    description: 'LaTeX-based professional CV template. Clean academic style perfect for researchers and academics.',
    category: 'Academic',
    type: 'resume',
    previewImage: '/templates/previews/autocv.png',
    pdfUrl: '/autoCV.pdf',
    colorScheme: ['#000000', '#FFFFFF', '#1F2937', '#4B5563'],
    tags: ['Academic', 'LaTeX', 'Research', 'Professional', 'Clean'],
    difficulty: 'professional',
    isPro: false,
    isFeatured: true,
    rating: 4.7,
    downloads: 8900,
    author: {
      name: 'AutoCV',
      verified: true,
    },
  },
  {
    id: 'altacv-template',
    title: 'AltaCV Template',
    description: 'Modern alternative CV template with sidebar. Perfect for creative professionals and designers.',
    category: 'Creative',
    type: 'resume',
    previewImage: '/templates/previews/altacv.png',
    pdfUrl: '/AltaCV_Template.pdf',
    colorScheme: ['#7C3AED', '#FFFFFF', '#6D28D9', '#8B5CF6'],
    tags: ['Creative', 'Modern', 'Sidebar', 'Designer', 'Colorful'],
    difficulty: 'intermediate',
    isPro: true,
    isFeatured: true,
    rating: 4.8,
    downloads: 14200,
    author: {
      name: 'AltaCV',
      verified: true,
    },
  },
  {
    id: 'black-white-professional',
    title: 'Black & White Professional',
    description: 'Clean and minimalist ATS-friendly resume. Perfect for corporate jobs, tech roles, and professional positions.',
    category: 'Corporate',
    type: 'resume',
    previewImage: '/templates/previews/black-white-professional.png',
    pdfUrl: '/Black and White Clean Professional A4 Resume.pdf',
    colorScheme: ['#000000', '#FFFFFF', '#333333', '#666666'],
    tags: ['Professional', 'ATS-Friendly', 'Minimalist', 'Corporate', 'Clean'],
    difficulty: 'beginner',
    isPro: false,
    isFeatured: true,
    rating: 4.9,
    downloads: 15420,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'blue-white-modern-professional',
    title: 'Blue & White Modern',
    description: 'Modern professional resume with blue accents. Clean layout perfect for tech and business professionals.',
    category: 'Modern',
    type: 'resume',
    previewImage: '/templates/previews/blue-white-modern-professional.png',
    pdfUrl: '/Blue and White Modern Professional Resume.pdf',
    colorScheme: ['#2563EB', '#FFFFFF', '#1E40AF', '#F8FAFC'],
    tags: ['Modern', 'Professional', 'Blue', 'Tech', 'Business'],
    difficulty: 'beginner',
    isPro: false,
    isFeatured: true,
    rating: 4.8,
    downloads: 12890,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'blue-black-geometric-creative',
    title: 'Geometric Creative',
    description: 'Creative resume with geometric design elements. Stand out with modern blue and black styling.',
    category: 'Creative',
    type: 'resume',
    previewImage: '/templates/previews/blue-black-geometric-creative.png',
    pdfUrl: '/Blue and Black Geometric Creative Resume.pdf',
    colorScheme: ['#1E3A8A', '#000000', '#3B82F6', '#F3F4F6'],
    tags: ['Creative', 'Geometric', 'Modern', 'Designer', 'Unique'],
    difficulty: 'intermediate',
    isPro: false,
    isFeatured: false,
    rating: 4.7,
    downloads: 9560,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'it-manager-cv',
    title: 'IT Manager CV',
    description: 'Professional CV template designed for IT managers and technical leaders. Comprehensive layout for extensive experience.',
    category: 'Technology',
    type: 'resume',
    previewImage: '/templates/previews/it-manager-cv.png',
    pdfUrl: '/IT Manager CV Resume.pdf',
    colorScheme: ['#0F172A', '#3B82F6', '#64748B', '#F1F5F9'],
    tags: ['IT', 'Manager', 'Technical', 'Leadership', 'Professional'],
    difficulty: 'professional',
    isPro: false,
    isFeatured: true,
    rating: 4.9,
    downloads: 11230,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },

  // PRESENTATION TEMPLATES
  {
    id: 'blue-green-ai-presentation',
    title: 'AI & Technology Presentation',
    description: 'Modern blue and green design for artificial intelligence and tech presentations. Professional slides with clean layouts.',
    category: 'Technology',
    type: 'presentation',
    previewImage: '/templates/previews/blue-green-ai-presentation-slide-1.png',
    previewImages: [
      '/templates/previews/blue-green-ai-presentation-slide-1.png',
      '/templates/previews/blue-green-ai-presentation-slide-2.png',
      '/templates/previews/blue-green-ai-presentation-slide-3.png',
      '/templates/previews/blue-green-ai-presentation-slide-4.png',
      '/templates/previews/blue-green-ai-presentation-slide-5.png',
      '/templates/previews/blue-green-ai-presentation-slide-6.png',
      '/templates/previews/blue-green-ai-presentation-slide-7.png',
      '/templates/previews/blue-green-ai-presentation-slide-8.png',
      '/templates/previews/blue-green-ai-presentation-slide-9.png',
      '/templates/previews/blue-green-ai-presentation-slide-10.png',
    ],
    pdfUrl: '/Blue and Green Modern Artificial Intelligence Presentation.pdf',
    colorScheme: ['#2563EB', '#10B981', '#1E293B', '#F8FAFC'],
    tags: ['AI', 'Technology', 'Modern', 'Professional', 'Business'],
    difficulty: 'intermediate',
    isPro: false,
    isFeatured: true,
    rating: 4.8,
    downloads: 8750,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'black-elegant-startup-pitch',
    title: 'Startup Pitch Deck',
    description: 'Black elegant and modern pitch deck presentation for startups. Perfect for investor presentations and business proposals.',
    category: 'Business',
    type: 'presentation',
    previewImage: '/templates/previews/black-elegant-startup-pitch-slide-1.png',
    previewImages: [
      '/templates/previews/black-elegant-startup-pitch-slide-1.png',
      '/templates/previews/black-elegant-startup-pitch-slide-2.png',
      '/templates/previews/black-elegant-startup-pitch-slide-3.png',
      '/templates/previews/black-elegant-startup-pitch-slide-4.png',
      '/templates/previews/black-elegant-startup-pitch-slide-5.png',
      '/templates/previews/black-elegant-startup-pitch-slide-6.png',
      '/templates/previews/black-elegant-startup-pitch-slide-7.png',
      '/templates/previews/black-elegant-startup-pitch-slide-8.png',
      '/templates/previews/black-elegant-startup-pitch-slide-9.png',
      '/templates/previews/black-elegant-startup-pitch-slide-10.png',
      '/templates/previews/black-elegant-startup-pitch-slide-11.png',
      '/templates/previews/black-elegant-startup-pitch-slide-12.png',
      '/templates/previews/black-elegant-startup-pitch-slide-13.png',
      '/templates/previews/black-elegant-startup-pitch-slide-14.png',
      '/templates/previews/black-elegant-startup-pitch-slide-15.png',
    ],
    pdfUrl: '/Black Elegant and Modern Startup Pitch Deck Presentation.pdf',
    colorScheme: ['#000000', '#FFFFFF', '#1F2937', '#F3F4F6'],
    tags: ['Startup', 'Pitch Deck', 'Business', 'Elegant', 'Professional'],
    difficulty: 'professional',
    isPro: false,
    isFeatured: true,
    rating: 4.9,
    downloads: 12340,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'black-grey-3d-tech',
    title: '3D Tech Company',
    description: 'Black and grey 3D shapes tech company presentation. Modern design for technology businesses.',
    category: 'Technology',
    type: 'presentation',
    previewImage: '/templates/previews/black-grey-3d-tech-slide-1.png',
    previewImages: [
      '/templates/previews/black-grey-3d-tech-slide-1.png',
      '/templates/previews/black-grey-3d-tech-slide-2.png',
      '/templates/previews/black-grey-3d-tech-slide-3.png',
      '/templates/previews/black-grey-3d-tech-slide-4.png',
      '/templates/previews/black-grey-3d-tech-slide-5.png',
      '/templates/previews/black-grey-3d-tech-slide-6.png',
      '/templates/previews/black-grey-3d-tech-slide-7.png',
      '/templates/previews/black-grey-3d-tech-slide-8.png',
      '/templates/previews/black-grey-3d-tech-slide-9.png',
      '/templates/previews/black-grey-3d-tech-slide-10.png',
    ],
    pdfUrl: '/Black and Grey 3D Shapes Tech Company Presentation.pdf',
    colorScheme: ['#000000', '#6B7280', '#1F2937', '#F3F4F6'],
    tags: ['Tech', '3D', 'Modern', 'Company', 'Professional'],
    difficulty: 'intermediate',
    isPro: false,
    isFeatured: false,
    rating: 4.7,
    downloads: 8920,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'blue-white-modern-ai',
    title: 'Modern AI Presentation',
    description: 'Blue and white modern artificial intelligence presentation. Perfect for AI and tech presentations.',
    category: 'Technology',
    type: 'presentation',
    previewImage: '/templates/previews/blue-white-modern-ai-slide-1.png',
    previewImages: [
      '/templates/previews/blue-white-modern-ai-slide-1.png',
      '/templates/previews/blue-white-modern-ai-slide-2.png',
      '/templates/previews/blue-white-modern-ai-slide-3.png',
      '/templates/previews/blue-white-modern-ai-slide-4.png',
      '/templates/previews/blue-white-modern-ai-slide-5.png',
      '/templates/previews/blue-white-modern-ai-slide-6.png',
      '/templates/previews/blue-white-modern-ai-slide-7.png',
      '/templates/previews/blue-white-modern-ai-slide-8.png',
      '/templates/previews/blue-white-modern-ai-slide-9.png',
      '/templates/previews/blue-white-modern-ai-slide-10.png',
    ],
    pdfUrl: '/Blue and White Modern Artificial Intelligence Presentation.pdf',
    colorScheme: ['#2563EB', '#FFFFFF', '#1E40AF', '#EFF6FF'],
    tags: ['AI', 'Modern', 'Blue', 'Technology', 'Clean'],
    difficulty: 'intermediate',
    isPro: false,
    isFeatured: true,
    rating: 4.8,
    downloads: 10450,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'beige-black-minimalist-project',
    title: 'Minimalist Project Deck',
    description: 'Beige and black minimalist project deck presentation. Clean and professional for project proposals.',
    category: 'Business',
    type: 'presentation',
    previewImage: '/templates/previews/beige-black-minimalist-project-slide-1.png',
    previewImages: [
      '/templates/previews/beige-black-minimalist-project-slide-1.png',
      '/templates/previews/beige-black-minimalist-project-slide-2.png',
      '/templates/previews/beige-black-minimalist-project-slide-3.png',
      '/templates/previews/beige-black-minimalist-project-slide-4.png',
      '/templates/previews/beige-black-minimalist-project-slide-5.png',
      '/templates/previews/beige-black-minimalist-project-slide-6.png',
      '/templates/previews/beige-black-minimalist-project-slide-7.png',
      '/templates/previews/beige-black-minimalist-project-slide-8.png',
      '/templates/previews/beige-black-minimalist-project-slide-9.png',
      '/templates/previews/beige-black-minimalist-project-slide-10.png',
    ],
    pdfUrl: '/Beige and Black Minimalist Project Deck Presentation.pdf',
    colorScheme: ['#F5F5DC', '#000000', '#8B7355', '#FFFFFF'],
    tags: ['Minimalist', 'Project', 'Business', 'Clean', 'Professional'],
    difficulty: 'beginner',
    isPro: false,
    isFeatured: false,
    rating: 4.6,
    downloads: 7680,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
  {
    id: 'white-blue-sales-strategy',
    title: 'Sales Strategy',
    description: 'White blue simple modern enhancing sales strategy presentation. Perfect for sales and marketing teams.',
    category: 'Marketing',
    type: 'presentation',
    previewImage: '/templates/previews/white-blue-sales-strategy-slide-1.png',
    previewImages: [
      '/templates/previews/white-blue-sales-strategy-slide-1.png',
      '/templates/previews/white-blue-sales-strategy-slide-2.png',
      '/templates/previews/white-blue-sales-strategy-slide-3.png',
      '/templates/previews/white-blue-sales-strategy-slide-4.png',
      '/templates/previews/white-blue-sales-strategy-slide-5.png',
      '/templates/previews/white-blue-sales-strategy-slide-6.png',
      '/templates/previews/white-blue-sales-strategy-slide-7.png',
      '/templates/previews/white-blue-sales-strategy-slide-8.png',
      '/templates/previews/white-blue-sales-strategy-slide-9.png',
      '/templates/previews/white-blue-sales-strategy-slide-10.png',
    ],
    pdfUrl: '/White Blue Simple Modern Enhancing Sales Strategy Presentation.pdf',
    colorScheme: ['#FFFFFF', '#3B82F6', '#1E40AF', '#DBEAFE'],
    tags: ['Sales', 'Marketing', 'Strategy', 'Modern', 'Business'],
    difficulty: 'intermediate',
    isPro: false,
    isFeatured: true,
    rating: 4.8,
    downloads: 9340,
    author: {
      name: 'DraftDeckAI Team',
      verified: true,
    },
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All Templates', count: RESUME_TEMPLATES.length },
  { id: 'resume', label: 'Resume', count: RESUME_TEMPLATES.filter(t => t.type === 'resume').length },
  { id: 'presentation', label: 'Presentation', count: RESUME_TEMPLATES.filter(t => t.type === 'presentation').length },
];
