// Security configuration and utilities

export const SECURITY_CONFIG = {
  // Rate limiting
  RATE_LIMITS: {
    AUTH: { requests: 10, windowMs: 15 * 60 * 1000 }, // 10 requests per 15 minutes
    GENERATE: { requests: 20, windowMs: 15 * 60 * 1000 }, // 20 requests per 15 minutes
    API: { requests: 100, windowMs: 15 * 60 * 1000 }, // 100 requests per 15 minutes
  },

  // Input validation limits
  INPUT_LIMITS: {
    NAME_MAX_LENGTH: 100,
    EMAIL_MAX_LENGTH: 254,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 128,
    PROMPT_MAX_LENGTH: 5000,
    CONTENT_MAX_LENGTH: 10000,
  },

  // Allowed file types for uploads
  ALLOWED_FILE_TYPES: [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ],

  // Maximum file size (5MB)
  MAX_FILE_SIZE: 5 * 1024 * 1024,

  // Session configuration
  SESSION: {
    MAX_AGE: 24 * 60 * 60, // 24 hours
    REFRESH_THRESHOLD: 60 * 60, // 1 hour
  },
};

// Security headers for different environments
export const getSecurityHeaders = (isDevelopment: boolean = false) => {
  const baseHeaders = {
    'X-Frame-Options': 'DENY',
    'X-Content-Type-Options': 'nosniff',
    'X-XSS-Protection': '1; mode=block',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
  };

  // Common CSP directives
  const cspDirectives = [
    "default-src 'self'",
    "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://js.stripe.com https://cdn.jsdelivr.net",
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net",
    "font-src 'self' https://fonts.gstatic.com data: https://cdn.jsdelivr.net",
    "img-src 'self' data: https: blob:",
    // SECURITY NOTE: data: URIs in connect-src are ONLY needed for @react-pdf/renderer's yoga-wasm module
    // which loads the WASM layout engine via a data: URI. This is a controlled, safe use case as:
    // 1. The data URI is generated by the trusted @react-pdf/renderer library
    // 2. It only contains the yoga WASM binary, not user-controlled data
    // 3. Alternative approaches (blob: or external URLs) would increase attack surface
    // WARNING: This allows data: URIs globally in connect-src. Monitor for unintended usage in other network requests.
    // If this directive is ever removed, PDF generation will fail with CSP violations.
    "connect-src 'self' data: https://*.supabase.co https://*.nebius.cloud https://api.stripe.com https://generativelanguage.googleapis.com https://api.mistral.ai https://api.tokenfactory.nebius.com https://latexonline.cc https://latex.ytotech.com https://cdn.jsdelivr.net",
    "frame-src 'self' blob: https://js.stripe.com",
    "object-src 'self' blob:",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "worker-src 'self' blob:",
  ].join('; ');

  const headers = {
    ...baseHeaders,
    'Content-Security-Policy': cspDirectives,
  };

  if (!isDevelopment) {
    return {
      ...headers,
      'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
    };
  }

  return headers;
};

// Validate environment variables
export function validateEnvironmentVariables() {
  const required = [
    'NEXT_PUBLIC_SUPABASE_URL',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    'GEMINI_API_KEY',
  ];

  const missing = required.filter(key => !process.env[key]);

  if (missing.length > 0) {
    throw new Error(`Missing required environment variables: ${missing.join(', ')}`);
  }

  // Validate URL format
  try {
    new URL(process.env.NEXT_PUBLIC_SUPABASE_URL!);
  } catch {
    throw new Error('NEXT_PUBLIC_SUPABASE_URL must be a valid URL');
  }

  // Validate API key format (basic check)
  if (process.env.GEMINI_API_KEY!.length < 20) {
    throw new Error('GEMINI_API_KEY appears to be invalid');
  }
}

import { logger } from './logger';

// Log security events
export function logSecurityEvent(event: string, details: any, ip?: string) {
  const logEntry = {
    event,
    ip: ip || 'unknown',
    details,
  };

  // The logger handles environment checks and structured JSON output
  logger.warn(null, 'SECURITY_EVENT', logEntry);
}

// Rate limiting store: shared across the instance
const rateLimitStore = new Map<string, { count: number; reset: number }>();
const RATE_LIMIT_MAX_ENTRIES = 10_000;

function pruneExpired(now: number) {
  for (const [key, value] of rateLimitStore) {
    if (now > value.reset) rateLimitStore.delete(key);
  }
}

export interface RateLimitConfig {
  requests: number;
  windowMs: number;
}

/**
 * Reusable rate limiting utility.
 * Supports configurable request caps and time windows.
 */
export function checkRateLimit(
  identifier: string,
  config: RateLimitConfig
): { allowed: boolean; remaining: number; reset: number; retryAfter: number } {
  const now = Date.now();
  if (rateLimitStore.size > RATE_LIMIT_MAX_ENTRIES) pruneExpired(now);

  let data = rateLimitStore.get(identifier);

  if (!data || now > data.reset) {
    data = { count: 1, reset: now + config.windowMs };
    rateLimitStore.set(identifier, data);
    return {
      allowed: true,
      remaining: config.requests - 1,
      reset: data.reset,
      retryAfter: 0
    };
  }

  if (data.count >= config.requests) {
    return {
      allowed: false,
      remaining: 0,
      reset: data.reset,
      retryAfter: Math.ceil((data.reset - now) / 1000)
    };
  }

  data.count++;
  rateLimitStore.set(identifier, data);
  return {
    allowed: true,
    remaining: config.requests - data.count,
    reset: data.reset,
    retryAfter: 0
  };
}

// Check if request is from allowed origin
export function isAllowedOrigin(origin: string | null, host: string): boolean {
  if (!origin) return false;

  const allowedOrigins = [
    `https://${host}`,
    'https://draftdeckai.com',
    ...(process.env.NEXT_PUBLIC_VERCEL_URL ? [`https://${process.env.NEXT_PUBLIC_VERCEL_URL.replace(/^https?:\/\//, '')}`] : []),
  ];

  if (process.env.NODE_ENV === 'development') {
    allowedOrigins.push(
      'http://localhost:3000',
      'http://127.0.0.1:3000',
      'http://localhost:3001',
      'http://127.0.0.1:3001',
      'http://localhost:3002',
      'http://127.0.0.1:3002',
      'http://localhost:3003',
      'http://127.0.0.1:3003'
    );
  }

  return allowedOrigins.includes(origin);
}
